# oml-code settings
oml-code:
  schemaVersion: 1

# project npm settings
project:
  name: "@modelware/sierra-method"
  version: 0.1.0
  title: Sierra Method
  description: The Sierra modeling method

# source folders
sources:
  - src

# oml server settings
#server:
#  port: 8080

# packing settings
pack:
  - include: [src/method]

# oml-cli parameter defaults
defaults:
  export: -o build/owl
  render: -m src/model/md -b build/web -c src/model/oml/fireforce6.github.io/mission-control/bundle.oml
  pack: -o build/dist
