name: CD

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OML_PLATFORM_API_KEY: ${{ secrets.OML_PLATFORM_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Install Oml
        run: npm install -g @oml/cli

      - name: Version Oml
        run: oml -V

      - name: Render Oml
        run: oml render -md src/model/md -owl build/owl -web build/web -c src/model/oml/fireforce6.github.io/mission-control/bundle.oml

      - name: Rename _oml to oml (hack for jekyll)
        run: |
          mv build/web/_oml build/web/oml
          find build/web -type f \( -name "*.html" -o -name "*.js" -o -name "*.css" \) \
            -exec sed -i 's|/_oml/|/oml/|g' {} +

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: ${{ 'github-pages' }}
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
