name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          registry-url: https://registry.npmjs.org

      - name: Install Oml
        run: npm install -g @oml/cli

      - name: Version Oml
        run: oml -V

      - name: Lint Oml
        run: oml lint

      - name: Compile Oml
        run: oml compile -owl build/owl --only

      - name: Reason Oml
        run: oml reason -owl build/owl --only

      - name: Validate Oml
        run: oml validate -md src/model/md -owl build/owl --only
